AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'Vagrantfile'
    - 'app/jobs/product_load.rb'

Rails:
  Enabled: true

LineLength:
  Description: 'Limit lines to 120 characters.'
  Enabled: true
  Max: 120

MethodLength:
  Enabled: false

ClassLength:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

NumericLiterals:
  MinDigits: 6

CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# Causes false positives in Atom
Style/FileName:
  Description: 'Use snake_case for source file names.'
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/CaseIndentation:
  IndentWhenRelativeTo: end

Rails/HasAndBelongsToMany:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
