default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:

development:
  <<: *default
  database: batman_development

test:
  <<: *default
  database: batman_test

production:
  <<: *default
  host: ec2-184-73-165-195.compute-1.amazonaws.com
  database: d9499l7m4r45br
  username: hifkiolcsmsuyl
  password: g_x7ZW6PLj1hXDJDMTlLFHQ7J2
