default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: batman
  password:

development:
  <<: *default
  database: batman_development

test:
  <<: *default
  database: batman_test

production:
  <<: *default
  database: batman_production
  username: batman
